### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by SandroCoutinho** [mtscout6/uebersicht-github-notifications#3]
![image](https://user-images.githubusercontent.com/5498024/36068593-a43be3b4-0ed0-11e8-9242-67a161cd93d3.png)

**Comment by SandroCoutinho** [comment]
Fixed it by changing `github-notifications.widget` to `uebersicht-github-notifications`

**Comment by pquimby** [comment]
I experienced this issue and the solution mentioned by @SandroCoutinho fixed it. Since this issue will affect anyone with the same default unzipped directory name, fixing it in the codebase seems like it will do the right thing for most users who find and download the widget. See PR #4.
